config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  get '/user' => "users#index"
  post '/songs' => "songs#submit"
  post "users_veto" => "users#veto"
  post "song_veto" => "songs#veto"
  post "song_vote" => "songs#vote"
  get "/playlist" => "playlists#show"

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :votes
  has_many :users, through: :votes
  belongs_to :playlist_id
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :votes
  has_many :songs, through: :votes

   def vote
   end

   def suggest
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :song
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # before_action :authenticate_user!

  def show
     @playlist= Song.where(veto:nil).order(name: :asc)
    @new_playlist = []
    @new_playlist2 = []
    @new_playlist3 = []
    @playlist.each do |song|
      @new_playlist << [song.name[0],[song.votes.count,song.name,song.artist]]
    end

    while @new_playlist.length>1
      if @new_playlist[0][0]!=@new_playlist[1][0]
         @new_playlist2+=@new_playlist.shift
      elsif @new_playlist[0][1][0] > @new_playlist[1][1][0]
         @new_playlist2+=@new_playlist.shift
        @new_playlist.shift
      else
         @new_playlist.shift
      end
    end
    if @new_playlist.length == 1
      @new_playlist2+=@new_playlist
    end
    (@new_playlist2.length).times do |i|
      if i.odd?
        @new_playlist3+=[@new_playlist2[i]]
      end
    end
    if @new_playlist.length == 1
      @new_playlist3+= [@new_playlist[0][1]]
    end



  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def show
    @songs = Song.all
    render 'users/index'
  end

  def submit
    isthere = 0
    songs = Song.all
    count = songs.count
    count.times do |i|
    s = songs[i]
      if s.artist == song_params[:artist] && s.name == song_params[:name]
        flash[:alert] = "Song is already in the playlist!"
        isthere = 1
        break
      end
    end
    if isthere!=1
      @song = Song.create(song_params)
    end
    show
  end

  def veto
    if current_user.veto_remaining == 1
      Song.destroy(Song.where(artist: song_params[:artist], name: song_params[:name]))
      Song.create(user_id: song_params[:user_id],artist: song_params[:artist], name: song_params[:name], veto: true)
      current_user.update_attribute(:veto_remaining, 0)
     else
      flash[:alert] = "You have no vetos remaining!"
     end
    render 'users/index'
  end

  def vote
    song = Song.where(artist:song_params[:artist],name:song_params[:name])
    if current_user.votes.count < 15
     vote = current_user.votes.create(song_id:song[0].id)
     flash[:notice] = "You have #{15-current_user.votes.count} remaining"
   else
     flash[:alert] = "You have reached your maximum number of votes"
   end
   render 'users/index'
  end

  private
  def song_params
    params.require(:song).permit(:user_id, :name, :artist)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    if params[:query]
      @query = RSpotify::Track.search(params[:query], limit: 10)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotibetical</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     <%= link_to "Home", root_path%> |
     <%= render 'devise/menu/registration_items' %>|
     <%= render 'devise/menu/login_items' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/playlists/show.html.erb
<h2> Playlist this week <h3>
<table>
  <thead>
    <tr>
      <td> SONGS </td>
      <td> ARTIST </td>
      <td> VOTES </td>
    </tr>
  </thead>
  <tbody>
    <%@new_playlist3.each do |array| %>
      <tr>
        <td><%=array[1]%></td>
        <td><%=array[2]%></td>
        <td><%=array[0]%></td>
      </tr>
      <%end%>
  </tbody>
</table>
<!-- <%=@new_playlist%>
-----------
<%=@new_playlist2%>
-----------
<%=@new_playlist3%> -->

app/views/users/index.html.erb
<h1> Welcome to Spotibetical!</h1>
<header>
  <%= form_tag("user", method: "get") do %>
  <%= text_field_tag(:query, params[:query], placeholder: "Look for a song!") %>
  <%= submit_tag("Search") %>
  <% end %>
</header>
<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3> Your search results... </h3>
      <table>
        <thead>
          <tr>
            <th>SONG</th>
            <th>ARTIST</th>
            <th>ALBUM</th>
            <th>TIME</th>
          </tr>
        </thead>
        <tbody>
          <% if @query %>
            <% @query.each do |song| %>
            <% time = song.duration_ms%>
            <% seconds=(time/1000)%60 %>
            <% if seconds < 10 %>
              <% seconds = '0'+seconds.to_s %>
            <% end %>
            <% minutes=(time/(1000*60))%60 %>
            <tr>
              <td><%=song.name%></td>
              <td><%= song.artists[0].name %></td>
              <td><%= song.album.name %></td>
              <td><%=minutes%>:<%=seconds%></td>
              <td class="col-md-2"> <%= button_to "+", songs_path(song:{
                                                                  :user_id => current_user.id,
                                                                  :name => song.name,
                                                                  :artist => song.artists[0].name}) %></td>
            </tr>
            <% end %>
          <%end%>
        </tbody>
      </table>
    </div>
    <div class="col-md-5">
      <h3> Vote for songs here! </h3>
      <table>
        <tbody>
          <% if Song.all %>
            <% Song.all.each do |song| %>
              <tr>
                <td><%= song.name %></td>
                <td><%= song.artist %></td>
                <% if song.veto != true %>
                  <td> <%= button_to "\u2191  #{song.votes.length}", song_vote_path(song:{:user_id => current_user.id,
                                                                    :name => song.name,
                                                                    :artist => song.artist}) %></td>
                <%end%>
                <% if song.veto != true && current_user.veto_remaining!=0%>
                  <td> <%= button_to "x", song_veto_path(song:{:name => song.name,
                                                             :artist => song.artist}) %>
                <%end%>
              </tr>
            <%end%>
          <%end%>
        </tbody>
    </table>
    </div>
  </div>
  <%= link_to "This week's playlist", playlist_path %>
</div>
<% else %>
<h4> You must login to continue </h4>
<%end%>